// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-firebase/internal/data/ent/devicetoken"
	"go-firebase/internal/data/ent/user"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DeviceTokenCreate is the builder for creating a DeviceToken entity.
type DeviceTokenCreate struct {
	config
	mutation *DeviceTokenMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeviceTokenCreate) SetCreatedAt(v time.Time) *DeviceTokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeviceTokenCreate) SetNillableCreatedAt(v *time.Time) *DeviceTokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DeviceTokenCreate) SetUpdatedAt(v time.Time) *DeviceTokenCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DeviceTokenCreate) SetNillableUpdatedAt(v *time.Time) *DeviceTokenCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *DeviceTokenCreate) SetUserID(v uuid.UUID) *DeviceTokenCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetToken sets the "token" field.
func (_c *DeviceTokenCreate) SetToken(v string) *DeviceTokenCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *DeviceTokenCreate) SetPlatform(v string) *DeviceTokenCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *DeviceTokenCreate) SetNillablePlatform(v *string) *DeviceTokenCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetLastSeen sets the "last_seen" field.
func (_c *DeviceTokenCreate) SetLastSeen(v time.Time) *DeviceTokenCreate {
	_c.mutation.SetLastSeen(v)
	return _c
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_c *DeviceTokenCreate) SetNillableLastSeen(v *time.Time) *DeviceTokenCreate {
	if v != nil {
		_c.SetLastSeen(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *DeviceTokenCreate) SetIsActive(v bool) *DeviceTokenCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *DeviceTokenCreate) SetNillableIsActive(v *bool) *DeviceTokenCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DeviceTokenCreate) SetID(v uuid.UUID) *DeviceTokenCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DeviceTokenCreate) SetNillableID(v *uuid.UUID) *DeviceTokenCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *DeviceTokenCreate) SetUser(v *User) *DeviceTokenCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the DeviceTokenMutation object of the builder.
func (_c *DeviceTokenCreate) Mutation() *DeviceTokenMutation {
	return _c.mutation
}

// Save creates the DeviceToken in the database.
func (_c *DeviceTokenCreate) Save(ctx context.Context) (*DeviceToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeviceTokenCreate) SaveX(ctx context.Context) *DeviceToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeviceTokenCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := devicetoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := devicetoken.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Platform(); !ok {
		v := devicetoken.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.LastSeen(); !ok {
		v := devicetoken.DefaultLastSeen()
		_c.mutation.SetLastSeen(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := devicetoken.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := devicetoken.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeviceTokenCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DeviceToken.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DeviceToken.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "DeviceToken.user_id"`)}
	}
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "DeviceToken.token"`)}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "DeviceToken.platform"`)}
	}
	if _, ok := _c.mutation.LastSeen(); !ok {
		return &ValidationError{Name: "last_seen", err: errors.New(`ent: missing required field "DeviceToken.last_seen"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "DeviceToken.is_active"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "DeviceToken.user"`)}
	}
	return nil
}

func (_c *DeviceTokenCreate) sqlSave(ctx context.Context) (*DeviceToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeviceTokenCreate) createSpec() (*DeviceToken, *sqlgraph.CreateSpec) {
	var (
		_node = &DeviceToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(devicetoken.Table, sqlgraph.NewFieldSpec(devicetoken.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(devicetoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(devicetoken.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(devicetoken.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(devicetoken.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.LastSeen(); ok {
		_spec.SetField(devicetoken.FieldLastSeen, field.TypeTime, value)
		_node.LastSeen = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(devicetoken.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   devicetoken.UserTable,
			Columns: []string{devicetoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DeviceToken.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeviceTokenUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DeviceTokenCreate) OnConflict(opts ...sql.ConflictOption) *DeviceTokenUpsertOne {
	_c.conflict = opts
	return &DeviceTokenUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DeviceToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeviceTokenCreate) OnConflictColumns(columns ...string) *DeviceTokenUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeviceTokenUpsertOne{
		create: _c,
	}
}

type (
	// DeviceTokenUpsertOne is the builder for "upsert"-ing
	//  one DeviceToken node.
	DeviceTokenUpsertOne struct {
		create *DeviceTokenCreate
	}

	// DeviceTokenUpsert is the "OnConflict" setter.
	DeviceTokenUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *DeviceTokenUpsert) SetUpdatedAt(v time.Time) *DeviceTokenUpsert {
	u.Set(devicetoken.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeviceTokenUpsert) UpdateUpdatedAt() *DeviceTokenUpsert {
	u.SetExcluded(devicetoken.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *DeviceTokenUpsert) SetUserID(v uuid.UUID) *DeviceTokenUpsert {
	u.Set(devicetoken.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DeviceTokenUpsert) UpdateUserID() *DeviceTokenUpsert {
	u.SetExcluded(devicetoken.FieldUserID)
	return u
}

// SetToken sets the "token" field.
func (u *DeviceTokenUpsert) SetToken(v string) *DeviceTokenUpsert {
	u.Set(devicetoken.FieldToken, v)
	return u
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *DeviceTokenUpsert) UpdateToken() *DeviceTokenUpsert {
	u.SetExcluded(devicetoken.FieldToken)
	return u
}

// SetPlatform sets the "platform" field.
func (u *DeviceTokenUpsert) SetPlatform(v string) *DeviceTokenUpsert {
	u.Set(devicetoken.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *DeviceTokenUpsert) UpdatePlatform() *DeviceTokenUpsert {
	u.SetExcluded(devicetoken.FieldPlatform)
	return u
}

// SetLastSeen sets the "last_seen" field.
func (u *DeviceTokenUpsert) SetLastSeen(v time.Time) *DeviceTokenUpsert {
	u.Set(devicetoken.FieldLastSeen, v)
	return u
}

// UpdateLastSeen sets the "last_seen" field to the value that was provided on create.
func (u *DeviceTokenUpsert) UpdateLastSeen() *DeviceTokenUpsert {
	u.SetExcluded(devicetoken.FieldLastSeen)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *DeviceTokenUpsert) SetIsActive(v bool) *DeviceTokenUpsert {
	u.Set(devicetoken.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *DeviceTokenUpsert) UpdateIsActive() *DeviceTokenUpsert {
	u.SetExcluded(devicetoken.FieldIsActive)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DeviceToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(devicetoken.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DeviceTokenUpsertOne) UpdateNewValues() *DeviceTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(devicetoken.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(devicetoken.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DeviceToken.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DeviceTokenUpsertOne) Ignore() *DeviceTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeviceTokenUpsertOne) DoNothing() *DeviceTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeviceTokenCreate.OnConflict
// documentation for more info.
func (u *DeviceTokenUpsertOne) Update(set func(*DeviceTokenUpsert)) *DeviceTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeviceTokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeviceTokenUpsertOne) SetUpdatedAt(v time.Time) *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeviceTokenUpsertOne) UpdateUpdatedAt() *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *DeviceTokenUpsertOne) SetUserID(v uuid.UUID) *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DeviceTokenUpsertOne) UpdateUserID() *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdateUserID()
	})
}

// SetToken sets the "token" field.
func (u *DeviceTokenUpsertOne) SetToken(v string) *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetToken(v)
	})
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *DeviceTokenUpsertOne) UpdateToken() *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdateToken()
	})
}

// SetPlatform sets the "platform" field.
func (u *DeviceTokenUpsertOne) SetPlatform(v string) *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *DeviceTokenUpsertOne) UpdatePlatform() *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdatePlatform()
	})
}

// SetLastSeen sets the "last_seen" field.
func (u *DeviceTokenUpsertOne) SetLastSeen(v time.Time) *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetLastSeen(v)
	})
}

// UpdateLastSeen sets the "last_seen" field to the value that was provided on create.
func (u *DeviceTokenUpsertOne) UpdateLastSeen() *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdateLastSeen()
	})
}

// SetIsActive sets the "is_active" field.
func (u *DeviceTokenUpsertOne) SetIsActive(v bool) *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *DeviceTokenUpsertOne) UpdateIsActive() *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdateIsActive()
	})
}

// Exec executes the query.
func (u *DeviceTokenUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeviceTokenCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeviceTokenUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DeviceTokenUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DeviceTokenUpsertOne.ID is not supported by MySQL driver. Use DeviceTokenUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DeviceTokenUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DeviceTokenCreateBulk is the builder for creating many DeviceToken entities in bulk.
type DeviceTokenCreateBulk struct {
	config
	err      error
	builders []*DeviceTokenCreate
	conflict []sql.ConflictOption
}

// Save creates the DeviceToken entities in the database.
func (_c *DeviceTokenCreateBulk) Save(ctx context.Context) ([]*DeviceToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DeviceToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeviceTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeviceTokenCreateBulk) SaveX(ctx context.Context) []*DeviceToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DeviceToken.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeviceTokenUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DeviceTokenCreateBulk) OnConflict(opts ...sql.ConflictOption) *DeviceTokenUpsertBulk {
	_c.conflict = opts
	return &DeviceTokenUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DeviceToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeviceTokenCreateBulk) OnConflictColumns(columns ...string) *DeviceTokenUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeviceTokenUpsertBulk{
		create: _c,
	}
}

// DeviceTokenUpsertBulk is the builder for "upsert"-ing
// a bulk of DeviceToken nodes.
type DeviceTokenUpsertBulk struct {
	create *DeviceTokenCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DeviceToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(devicetoken.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DeviceTokenUpsertBulk) UpdateNewValues() *DeviceTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(devicetoken.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(devicetoken.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DeviceToken.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DeviceTokenUpsertBulk) Ignore() *DeviceTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeviceTokenUpsertBulk) DoNothing() *DeviceTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeviceTokenCreateBulk.OnConflict
// documentation for more info.
func (u *DeviceTokenUpsertBulk) Update(set func(*DeviceTokenUpsert)) *DeviceTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeviceTokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeviceTokenUpsertBulk) SetUpdatedAt(v time.Time) *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeviceTokenUpsertBulk) UpdateUpdatedAt() *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *DeviceTokenUpsertBulk) SetUserID(v uuid.UUID) *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DeviceTokenUpsertBulk) UpdateUserID() *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdateUserID()
	})
}

// SetToken sets the "token" field.
func (u *DeviceTokenUpsertBulk) SetToken(v string) *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetToken(v)
	})
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *DeviceTokenUpsertBulk) UpdateToken() *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdateToken()
	})
}

// SetPlatform sets the "platform" field.
func (u *DeviceTokenUpsertBulk) SetPlatform(v string) *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *DeviceTokenUpsertBulk) UpdatePlatform() *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdatePlatform()
	})
}

// SetLastSeen sets the "last_seen" field.
func (u *DeviceTokenUpsertBulk) SetLastSeen(v time.Time) *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetLastSeen(v)
	})
}

// UpdateLastSeen sets the "last_seen" field to the value that was provided on create.
func (u *DeviceTokenUpsertBulk) UpdateLastSeen() *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdateLastSeen()
	})
}

// SetIsActive sets the "is_active" field.
func (u *DeviceTokenUpsertBulk) SetIsActive(v bool) *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *DeviceTokenUpsertBulk) UpdateIsActive() *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdateIsActive()
	})
}

// Exec executes the query.
func (u *DeviceTokenUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DeviceTokenCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeviceTokenCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeviceTokenUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
