// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-firebase/internal/data/ent/notificationtopic"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// NotificationTopic is the model entity for the NotificationTopic schema.
type NotificationTopic struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy *uuid.UUID `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy *uuid.UUID `json:"updated_by,omitempty"`
	// DeletedBy holds the value of the "deleted_by" field.
	DeletedBy *uuid.UUID `json:"deleted_by,omitempty"`
	// Deleted holds the value of the "deleted" field.
	Deleted bool `json:"deleted,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NotificationTopicQuery when eager-loading is set.
	Edges        NotificationTopicEdges `json:"edges"`
	selectValues sql.SelectValues
}

// NotificationTopicEdges holds the relations/edges for other nodes in the graph.
type NotificationTopicEdges struct {
	// UserNotificationTopics holds the value of the user_notification_topics edge.
	UserNotificationTopics []*UserNotificationTopic `json:"user_notification_topics,omitempty"`
	// Notifications holds the value of the notifications edge.
	Notifications []*Notification `json:"notifications,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserNotificationTopicsOrErr returns the UserNotificationTopics value or an error if the edge
// was not loaded in eager-loading.
func (e NotificationTopicEdges) UserNotificationTopicsOrErr() ([]*UserNotificationTopic, error) {
	if e.loadedTypes[0] {
		return e.UserNotificationTopics, nil
	}
	return nil, &NotLoadedError{edge: "user_notification_topics"}
}

// NotificationsOrErr returns the Notifications value or an error if the edge
// was not loaded in eager-loading.
func (e NotificationTopicEdges) NotificationsOrErr() ([]*Notification, error) {
	if e.loadedTypes[1] {
		return e.Notifications, nil
	}
	return nil, &NotLoadedError{edge: "notifications"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NotificationTopic) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notificationtopic.FieldCreatedBy, notificationtopic.FieldUpdatedBy, notificationtopic.FieldDeletedBy:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case notificationtopic.FieldDeleted:
			values[i] = new(sql.NullBool)
		case notificationtopic.FieldName, notificationtopic.FieldDescription:
			values[i] = new(sql.NullString)
		case notificationtopic.FieldCreatedAt, notificationtopic.FieldUpdatedAt, notificationtopic.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case notificationtopic.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NotificationTopic fields.
func (_m *NotificationTopic) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notificationtopic.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case notificationtopic.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case notificationtopic.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case notificationtopic.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case notificationtopic.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uuid.UUID)
				*_m.CreatedBy = *value.S.(*uuid.UUID)
			}
		case notificationtopic.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(uuid.UUID)
				*_m.UpdatedBy = *value.S.(*uuid.UUID)
			}
		case notificationtopic.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = new(uuid.UUID)
				*_m.DeletedBy = *value.S.(*uuid.UUID)
			}
		case notificationtopic.FieldDeleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field deleted", values[i])
			} else if value.Valid {
				_m.Deleted = value.Bool
			}
		case notificationtopic.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case notificationtopic.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NotificationTopic.
// This includes values selected through modifiers, order, etc.
func (_m *NotificationTopic) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUserNotificationTopics queries the "user_notification_topics" edge of the NotificationTopic entity.
func (_m *NotificationTopic) QueryUserNotificationTopics() *UserNotificationTopicQuery {
	return NewNotificationTopicClient(_m.config).QueryUserNotificationTopics(_m)
}

// QueryNotifications queries the "notifications" edge of the NotificationTopic entity.
func (_m *NotificationTopic) QueryNotifications() *NotificationQuery {
	return NewNotificationTopicClient(_m.config).QueryNotifications(_m)
}

// Update returns a builder for updating this NotificationTopic.
// Note that you need to call NotificationTopic.Unwrap() before calling this method if this NotificationTopic
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NotificationTopic) Update() *NotificationTopicUpdateOne {
	return NewNotificationTopicClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NotificationTopic entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NotificationTopic) Unwrap() *NotificationTopic {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NotificationTopic is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NotificationTopic) String() string {
	var builder strings.Builder
	builder.WriteString("NotificationTopic(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeletedBy; v != nil {
		builder.WriteString("deleted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("deleted=")
	builder.WriteString(fmt.Sprintf("%v", _m.Deleted))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteByte(')')
	return builder.String()
}

// NotificationTopics is a parsable slice of NotificationTopic.
type NotificationTopics []*NotificationTopic
