// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-firebase/internal/data/ent/permission"
	"go-firebase/internal/data/ent/role"
	"go-firebase/internal/data/ent/rolepermission"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RolePermissionCreate is the builder for creating a RolePermission entity.
type RolePermissionCreate struct {
	config
	mutation *RolePermissionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRoleID sets the "role_id" field.
func (_c *RolePermissionCreate) SetRoleID(v uuid.UUID) *RolePermissionCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetPermissionID sets the "permission_id" field.
func (_c *RolePermissionCreate) SetPermissionID(v uuid.UUID) *RolePermissionCreate {
	_c.mutation.SetPermissionID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *RolePermissionCreate) SetID(v uuid.UUID) *RolePermissionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RolePermissionCreate) SetNillableID(v *uuid.UUID) *RolePermissionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetRole sets the "role" edge to the Role entity.
func (_c *RolePermissionCreate) SetRole(v *Role) *RolePermissionCreate {
	return _c.SetRoleID(v.ID)
}

// SetPermission sets the "permission" edge to the Permission entity.
func (_c *RolePermissionCreate) SetPermission(v *Permission) *RolePermissionCreate {
	return _c.SetPermissionID(v.ID)
}

// Mutation returns the RolePermissionMutation object of the builder.
func (_c *RolePermissionCreate) Mutation() *RolePermissionMutation {
	return _c.mutation
}

// Save creates the RolePermission in the database.
func (_c *RolePermissionCreate) Save(ctx context.Context) (*RolePermission, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RolePermissionCreate) SaveX(ctx context.Context) *RolePermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RolePermissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RolePermissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RolePermissionCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := rolepermission.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RolePermissionCreate) check() error {
	if _, ok := _c.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "RolePermission.role_id"`)}
	}
	if _, ok := _c.mutation.PermissionID(); !ok {
		return &ValidationError{Name: "permission_id", err: errors.New(`ent: missing required field "RolePermission.permission_id"`)}
	}
	if len(_c.mutation.RoleIDs()) == 0 {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required edge "RolePermission.role"`)}
	}
	if len(_c.mutation.PermissionIDs()) == 0 {
		return &ValidationError{Name: "permission", err: errors.New(`ent: missing required edge "RolePermission.permission"`)}
	}
	return nil
}

func (_c *RolePermissionCreate) sqlSave(ctx context.Context) (*RolePermission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RolePermissionCreate) createSpec() (*RolePermission, *sqlgraph.CreateSpec) {
	var (
		_node = &RolePermission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rolepermission.Table, sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if nodes := _c.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolepermission.RoleTable,
			Columns: []string{rolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolepermission.PermissionTable,
			Columns: []string{rolepermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PermissionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RolePermission.Create().
//		SetRoleID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RolePermissionUpsert) {
//			SetRoleID(v+v).
//		}).
//		Exec(ctx)
func (_c *RolePermissionCreate) OnConflict(opts ...sql.ConflictOption) *RolePermissionUpsertOne {
	_c.conflict = opts
	return &RolePermissionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RolePermission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RolePermissionCreate) OnConflictColumns(columns ...string) *RolePermissionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RolePermissionUpsertOne{
		create: _c,
	}
}

type (
	// RolePermissionUpsertOne is the builder for "upsert"-ing
	//  one RolePermission node.
	RolePermissionUpsertOne struct {
		create *RolePermissionCreate
	}

	// RolePermissionUpsert is the "OnConflict" setter.
	RolePermissionUpsert struct {
		*sql.UpdateSet
	}
)

// SetRoleID sets the "role_id" field.
func (u *RolePermissionUpsert) SetRoleID(v uuid.UUID) *RolePermissionUpsert {
	u.Set(rolepermission.FieldRoleID, v)
	return u
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *RolePermissionUpsert) UpdateRoleID() *RolePermissionUpsert {
	u.SetExcluded(rolepermission.FieldRoleID)
	return u
}

// SetPermissionID sets the "permission_id" field.
func (u *RolePermissionUpsert) SetPermissionID(v uuid.UUID) *RolePermissionUpsert {
	u.Set(rolepermission.FieldPermissionID, v)
	return u
}

// UpdatePermissionID sets the "permission_id" field to the value that was provided on create.
func (u *RolePermissionUpsert) UpdatePermissionID() *RolePermissionUpsert {
	u.SetExcluded(rolepermission.FieldPermissionID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.RolePermission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(rolepermission.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RolePermissionUpsertOne) UpdateNewValues() *RolePermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(rolepermission.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RolePermission.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RolePermissionUpsertOne) Ignore() *RolePermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RolePermissionUpsertOne) DoNothing() *RolePermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RolePermissionCreate.OnConflict
// documentation for more info.
func (u *RolePermissionUpsertOne) Update(set func(*RolePermissionUpsert)) *RolePermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RolePermissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetRoleID sets the "role_id" field.
func (u *RolePermissionUpsertOne) SetRoleID(v uuid.UUID) *RolePermissionUpsertOne {
	return u.Update(func(s *RolePermissionUpsert) {
		s.SetRoleID(v)
	})
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *RolePermissionUpsertOne) UpdateRoleID() *RolePermissionUpsertOne {
	return u.Update(func(s *RolePermissionUpsert) {
		s.UpdateRoleID()
	})
}

// SetPermissionID sets the "permission_id" field.
func (u *RolePermissionUpsertOne) SetPermissionID(v uuid.UUID) *RolePermissionUpsertOne {
	return u.Update(func(s *RolePermissionUpsert) {
		s.SetPermissionID(v)
	})
}

// UpdatePermissionID sets the "permission_id" field to the value that was provided on create.
func (u *RolePermissionUpsertOne) UpdatePermissionID() *RolePermissionUpsertOne {
	return u.Update(func(s *RolePermissionUpsert) {
		s.UpdatePermissionID()
	})
}

// Exec executes the query.
func (u *RolePermissionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RolePermissionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RolePermissionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RolePermissionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: RolePermissionUpsertOne.ID is not supported by MySQL driver. Use RolePermissionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RolePermissionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RolePermissionCreateBulk is the builder for creating many RolePermission entities in bulk.
type RolePermissionCreateBulk struct {
	config
	err      error
	builders []*RolePermissionCreate
	conflict []sql.ConflictOption
}

// Save creates the RolePermission entities in the database.
func (_c *RolePermissionCreateBulk) Save(ctx context.Context) ([]*RolePermission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RolePermission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RolePermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RolePermissionCreateBulk) SaveX(ctx context.Context) []*RolePermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RolePermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RolePermissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RolePermission.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RolePermissionUpsert) {
//			SetRoleID(v+v).
//		}).
//		Exec(ctx)
func (_c *RolePermissionCreateBulk) OnConflict(opts ...sql.ConflictOption) *RolePermissionUpsertBulk {
	_c.conflict = opts
	return &RolePermissionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RolePermission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RolePermissionCreateBulk) OnConflictColumns(columns ...string) *RolePermissionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RolePermissionUpsertBulk{
		create: _c,
	}
}

// RolePermissionUpsertBulk is the builder for "upsert"-ing
// a bulk of RolePermission nodes.
type RolePermissionUpsertBulk struct {
	create *RolePermissionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RolePermission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(rolepermission.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RolePermissionUpsertBulk) UpdateNewValues() *RolePermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(rolepermission.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RolePermission.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RolePermissionUpsertBulk) Ignore() *RolePermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RolePermissionUpsertBulk) DoNothing() *RolePermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RolePermissionCreateBulk.OnConflict
// documentation for more info.
func (u *RolePermissionUpsertBulk) Update(set func(*RolePermissionUpsert)) *RolePermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RolePermissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetRoleID sets the "role_id" field.
func (u *RolePermissionUpsertBulk) SetRoleID(v uuid.UUID) *RolePermissionUpsertBulk {
	return u.Update(func(s *RolePermissionUpsert) {
		s.SetRoleID(v)
	})
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *RolePermissionUpsertBulk) UpdateRoleID() *RolePermissionUpsertBulk {
	return u.Update(func(s *RolePermissionUpsert) {
		s.UpdateRoleID()
	})
}

// SetPermissionID sets the "permission_id" field.
func (u *RolePermissionUpsertBulk) SetPermissionID(v uuid.UUID) *RolePermissionUpsertBulk {
	return u.Update(func(s *RolePermissionUpsert) {
		s.SetPermissionID(v)
	})
}

// UpdatePermissionID sets the "permission_id" field to the value that was provided on create.
func (u *RolePermissionUpsertBulk) UpdatePermissionID() *RolePermissionUpsertBulk {
	return u.Update(func(s *RolePermissionUpsert) {
		s.UpdatePermissionID()
	})
}

// Exec executes the query.
func (u *RolePermissionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RolePermissionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RolePermissionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RolePermissionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
