// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-firebase/internal/data/ent/devicetoken"
	"go-firebase/internal/data/ent/notification"
	"go-firebase/internal/data/ent/notificationtopic"
	"go-firebase/internal/data/ent/schema"
	"go-firebase/internal/data/ent/user"
	"go-firebase/internal/data/ent/usernotificationtopic"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	devicetokenMixin := schema.DeviceToken{}.Mixin()
	devicetokenMixinFields0 := devicetokenMixin[0].Fields()
	_ = devicetokenMixinFields0
	devicetokenFields := schema.DeviceToken{}.Fields()
	_ = devicetokenFields
	// devicetokenDescCreatedAt is the schema descriptor for created_at field.
	devicetokenDescCreatedAt := devicetokenMixinFields0[0].Descriptor()
	// devicetoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	devicetoken.DefaultCreatedAt = devicetokenDescCreatedAt.Default.(func() time.Time)
	// devicetokenDescUpdatedAt is the schema descriptor for updated_at field.
	devicetokenDescUpdatedAt := devicetokenMixinFields0[1].Descriptor()
	// devicetoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	devicetoken.DefaultUpdatedAt = devicetokenDescUpdatedAt.Default.(func() time.Time)
	// devicetoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	devicetoken.UpdateDefaultUpdatedAt = devicetokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	// devicetokenDescPlatform is the schema descriptor for platform field.
	devicetokenDescPlatform := devicetokenFields[3].Descriptor()
	// devicetoken.DefaultPlatform holds the default value on creation for the platform field.
	devicetoken.DefaultPlatform = devicetokenDescPlatform.Default.(string)
	// devicetokenDescLastSeen is the schema descriptor for last_seen field.
	devicetokenDescLastSeen := devicetokenFields[4].Descriptor()
	// devicetoken.DefaultLastSeen holds the default value on creation for the last_seen field.
	devicetoken.DefaultLastSeen = devicetokenDescLastSeen.Default.(func() time.Time)
	// devicetokenDescIsActive is the schema descriptor for is_active field.
	devicetokenDescIsActive := devicetokenFields[5].Descriptor()
	// devicetoken.DefaultIsActive holds the default value on creation for the is_active field.
	devicetoken.DefaultIsActive = devicetokenDescIsActive.Default.(bool)
	// devicetokenDescID is the schema descriptor for id field.
	devicetokenDescID := devicetokenFields[0].Descriptor()
	// devicetoken.DefaultID holds the default value on creation for the id field.
	devicetoken.DefaultID = devicetokenDescID.Default.(func() uuid.UUID)
	notificationMixin := schema.Notification{}.Mixin()
	notificationMixinFields0 := notificationMixin[0].Fields()
	_ = notificationMixinFields0
	notificationFields := schema.Notification{}.Fields()
	_ = notificationFields
	// notificationDescCreatedAt is the schema descriptor for created_at field.
	notificationDescCreatedAt := notificationMixinFields0[0].Descriptor()
	// notification.DefaultCreatedAt holds the default value on creation for the created_at field.
	notification.DefaultCreatedAt = notificationDescCreatedAt.Default.(func() time.Time)
	// notificationDescUpdatedAt is the schema descriptor for updated_at field.
	notificationDescUpdatedAt := notificationMixinFields0[1].Descriptor()
	// notification.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	notification.DefaultUpdatedAt = notificationDescUpdatedAt.Default.(func() time.Time)
	// notification.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	notification.UpdateDefaultUpdatedAt = notificationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// notificationDescSentAt is the schema descriptor for sent_at field.
	notificationDescSentAt := notificationFields[6].Descriptor()
	// notification.DefaultSentAt holds the default value on creation for the sent_at field.
	notification.DefaultSentAt = notificationDescSentAt.Default.(func() time.Time)
	// notificationDescIsRead is the schema descriptor for is_read field.
	notificationDescIsRead := notificationFields[7].Descriptor()
	// notification.DefaultIsRead holds the default value on creation for the is_read field.
	notification.DefaultIsRead = notificationDescIsRead.Default.(bool)
	// notificationDescID is the schema descriptor for id field.
	notificationDescID := notificationFields[0].Descriptor()
	// notification.DefaultID holds the default value on creation for the id field.
	notification.DefaultID = notificationDescID.Default.(func() uuid.UUID)
	notificationtopicMixin := schema.NotificationTopic{}.Mixin()
	notificationtopicMixinFields0 := notificationtopicMixin[0].Fields()
	_ = notificationtopicMixinFields0
	notificationtopicFields := schema.NotificationTopic{}.Fields()
	_ = notificationtopicFields
	// notificationtopicDescCreatedAt is the schema descriptor for created_at field.
	notificationtopicDescCreatedAt := notificationtopicMixinFields0[0].Descriptor()
	// notificationtopic.DefaultCreatedAt holds the default value on creation for the created_at field.
	notificationtopic.DefaultCreatedAt = notificationtopicDescCreatedAt.Default.(func() time.Time)
	// notificationtopicDescUpdatedAt is the schema descriptor for updated_at field.
	notificationtopicDescUpdatedAt := notificationtopicMixinFields0[1].Descriptor()
	// notificationtopic.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	notificationtopic.DefaultUpdatedAt = notificationtopicDescUpdatedAt.Default.(func() time.Time)
	// notificationtopic.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	notificationtopic.UpdateDefaultUpdatedAt = notificationtopicDescUpdatedAt.UpdateDefault.(func() time.Time)
	// notificationtopicDescID is the schema descriptor for id field.
	notificationtopicDescID := notificationtopicFields[0].Descriptor()
	// notificationtopic.DefaultID holds the default value on creation for the id field.
	notificationtopic.DefaultID = notificationtopicDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	usernotificationtopicFields := schema.UserNotificationTopic{}.Fields()
	_ = usernotificationtopicFields
	// usernotificationtopicDescSubscribedAt is the schema descriptor for subscribed_at field.
	usernotificationtopicDescSubscribedAt := usernotificationtopicFields[3].Descriptor()
	// usernotificationtopic.DefaultSubscribedAt holds the default value on creation for the subscribed_at field.
	usernotificationtopic.DefaultSubscribedAt = usernotificationtopicDescSubscribedAt.Default.(func() time.Time)
	// usernotificationtopicDescID is the schema descriptor for id field.
	usernotificationtopicDescID := usernotificationtopicFields[0].Descriptor()
	// usernotificationtopic.DefaultID holds the default value on creation for the id field.
	usernotificationtopic.DefaultID = usernotificationtopicDescID.Default.(func() uuid.UUID)
}
