// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-firebase/internal/data/ent/permission"
	"go-firebase/internal/data/ent/user"
	"go-firebase/internal/data/ent/userpermission"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserPermissionCreate is the builder for creating a UserPermission entity.
type UserPermissionCreate struct {
	config
	mutation *UserPermissionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserPermissionCreate) SetUserID(v uuid.UUID) *UserPermissionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPermissionID sets the "permission_id" field.
func (_c *UserPermissionCreate) SetPermissionID(v uuid.UUID) *UserPermissionCreate {
	_c.mutation.SetPermissionID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *UserPermissionCreate) SetID(v uuid.UUID) *UserPermissionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UserPermissionCreate) SetNillableID(v *uuid.UUID) *UserPermissionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserPermissionCreate) SetUser(v *User) *UserPermissionCreate {
	return _c.SetUserID(v.ID)
}

// SetPermission sets the "permission" edge to the Permission entity.
func (_c *UserPermissionCreate) SetPermission(v *Permission) *UserPermissionCreate {
	return _c.SetPermissionID(v.ID)
}

// Mutation returns the UserPermissionMutation object of the builder.
func (_c *UserPermissionCreate) Mutation() *UserPermissionMutation {
	return _c.mutation
}

// Save creates the UserPermission in the database.
func (_c *UserPermissionCreate) Save(ctx context.Context) (*UserPermission, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserPermissionCreate) SaveX(ctx context.Context) *UserPermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPermissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPermissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserPermissionCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := userpermission.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserPermissionCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserPermission.user_id"`)}
	}
	if _, ok := _c.mutation.PermissionID(); !ok {
		return &ValidationError{Name: "permission_id", err: errors.New(`ent: missing required field "UserPermission.permission_id"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserPermission.user"`)}
	}
	if len(_c.mutation.PermissionIDs()) == 0 {
		return &ValidationError{Name: "permission", err: errors.New(`ent: missing required edge "UserPermission.permission"`)}
	}
	return nil
}

func (_c *UserPermissionCreate) sqlSave(ctx context.Context) (*UserPermission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserPermissionCreate) createSpec() (*UserPermission, *sqlgraph.CreateSpec) {
	var (
		_node = &UserPermission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userpermission.Table, sqlgraph.NewFieldSpec(userpermission.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userpermission.UserTable,
			Columns: []string{userpermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userpermission.PermissionTable,
			Columns: []string{userpermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PermissionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserPermission.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserPermissionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserPermissionCreate) OnConflict(opts ...sql.ConflictOption) *UserPermissionUpsertOne {
	_c.conflict = opts
	return &UserPermissionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserPermission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserPermissionCreate) OnConflictColumns(columns ...string) *UserPermissionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserPermissionUpsertOne{
		create: _c,
	}
}

type (
	// UserPermissionUpsertOne is the builder for "upsert"-ing
	//  one UserPermission node.
	UserPermissionUpsertOne struct {
		create *UserPermissionCreate
	}

	// UserPermissionUpsert is the "OnConflict" setter.
	UserPermissionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserPermissionUpsert) SetUserID(v uuid.UUID) *UserPermissionUpsert {
	u.Set(userpermission.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserPermissionUpsert) UpdateUserID() *UserPermissionUpsert {
	u.SetExcluded(userpermission.FieldUserID)
	return u
}

// SetPermissionID sets the "permission_id" field.
func (u *UserPermissionUpsert) SetPermissionID(v uuid.UUID) *UserPermissionUpsert {
	u.Set(userpermission.FieldPermissionID, v)
	return u
}

// UpdatePermissionID sets the "permission_id" field to the value that was provided on create.
func (u *UserPermissionUpsert) UpdatePermissionID() *UserPermissionUpsert {
	u.SetExcluded(userpermission.FieldPermissionID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UserPermission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(userpermission.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserPermissionUpsertOne) UpdateNewValues() *UserPermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(userpermission.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserPermission.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserPermissionUpsertOne) Ignore() *UserPermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserPermissionUpsertOne) DoNothing() *UserPermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserPermissionCreate.OnConflict
// documentation for more info.
func (u *UserPermissionUpsertOne) Update(set func(*UserPermissionUpsert)) *UserPermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserPermissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserPermissionUpsertOne) SetUserID(v uuid.UUID) *UserPermissionUpsertOne {
	return u.Update(func(s *UserPermissionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserPermissionUpsertOne) UpdateUserID() *UserPermissionUpsertOne {
	return u.Update(func(s *UserPermissionUpsert) {
		s.UpdateUserID()
	})
}

// SetPermissionID sets the "permission_id" field.
func (u *UserPermissionUpsertOne) SetPermissionID(v uuid.UUID) *UserPermissionUpsertOne {
	return u.Update(func(s *UserPermissionUpsert) {
		s.SetPermissionID(v)
	})
}

// UpdatePermissionID sets the "permission_id" field to the value that was provided on create.
func (u *UserPermissionUpsertOne) UpdatePermissionID() *UserPermissionUpsertOne {
	return u.Update(func(s *UserPermissionUpsert) {
		s.UpdatePermissionID()
	})
}

// Exec executes the query.
func (u *UserPermissionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserPermissionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserPermissionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserPermissionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: UserPermissionUpsertOne.ID is not supported by MySQL driver. Use UserPermissionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserPermissionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserPermissionCreateBulk is the builder for creating many UserPermission entities in bulk.
type UserPermissionCreateBulk struct {
	config
	err      error
	builders []*UserPermissionCreate
	conflict []sql.ConflictOption
}

// Save creates the UserPermission entities in the database.
func (_c *UserPermissionCreateBulk) Save(ctx context.Context) ([]*UserPermission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserPermission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserPermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserPermissionCreateBulk) SaveX(ctx context.Context) []*UserPermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPermissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserPermission.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserPermissionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserPermissionCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserPermissionUpsertBulk {
	_c.conflict = opts
	return &UserPermissionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserPermission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserPermissionCreateBulk) OnConflictColumns(columns ...string) *UserPermissionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserPermissionUpsertBulk{
		create: _c,
	}
}

// UserPermissionUpsertBulk is the builder for "upsert"-ing
// a bulk of UserPermission nodes.
type UserPermissionUpsertBulk struct {
	create *UserPermissionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserPermission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(userpermission.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserPermissionUpsertBulk) UpdateNewValues() *UserPermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(userpermission.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserPermission.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserPermissionUpsertBulk) Ignore() *UserPermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserPermissionUpsertBulk) DoNothing() *UserPermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserPermissionCreateBulk.OnConflict
// documentation for more info.
func (u *UserPermissionUpsertBulk) Update(set func(*UserPermissionUpsert)) *UserPermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserPermissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserPermissionUpsertBulk) SetUserID(v uuid.UUID) *UserPermissionUpsertBulk {
	return u.Update(func(s *UserPermissionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserPermissionUpsertBulk) UpdateUserID() *UserPermissionUpsertBulk {
	return u.Update(func(s *UserPermissionUpsert) {
		s.UpdateUserID()
	})
}

// SetPermissionID sets the "permission_id" field.
func (u *UserPermissionUpsertBulk) SetPermissionID(v uuid.UUID) *UserPermissionUpsertBulk {
	return u.Update(func(s *UserPermissionUpsert) {
		s.SetPermissionID(v)
	})
}

// UpdatePermissionID sets the "permission_id" field to the value that was provided on create.
func (u *UserPermissionUpsertBulk) UpdatePermissionID() *UserPermissionUpsertBulk {
	return u.Update(func(s *UserPermissionUpsert) {
		s.UpdatePermissionID()
	})
}

// Exec executes the query.
func (u *UserPermissionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserPermissionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserPermissionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserPermissionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
