// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DeviceToken is the predicate function for devicetoken builders.
type DeviceToken func(*sql.Selector)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
