basePath: /api/v1
definitions:
  request.CreateNotificationTopicRequest:
    properties:
      topic_name:
        type: string
    required:
    - topic_name
    type: object
  request.CreateUserRequest:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    type: object
  request.LoginRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  request.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  request.RegisterDeviceRequest:
    properties:
      device_token:
        type: string
      identifier:
        description: e.g., user ID or email
        type: string
      platform:
        description: e.g., "ios", "android", "web"
        type: string
    required:
    - device_token
    - identifier
    - platform
    type: object
  request.SendNotificationRequest:
    properties:
      body:
        type: string
      payload:
        additionalProperties:
          type: string
        type: object
      title:
        type: string
      user_id:
        type: string
    required:
    - user_id
    type: object
  request.SubscribeNotificationTopicRequest:
    properties:
      topic_ids:
        items:
          type: string
        minItems: 1
        type: array
    required:
    - topic_ids
    type: object
  response.ApiResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
host: localhost:300
info:
  contact:
    email: ngdangkietswe@yopmail.com
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for a Go Firebase application.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Go Firebase API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns Firebase ID token.
      parameters:
      - description: Login Info
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: User Login
      tags:
      - Auth API
  /auth/me:
    get:
      consumes:
      - application/json
      description: Retrieves information about the currently authenticated user.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: Get Current User
      tags:
      - Auth API
  /auth/refresh-token:
    post:
      consumes:
      - application/json
      description: Refreshes the Firebase ID token using the provided refresh token.
      parameters:
      - description: Refresh Token Info
        in: body
        name: refresh
        required: true
        schema:
          $ref: '#/definitions/request.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: Refresh Firebase ID Token
      tags:
      - Auth API
  /auth/verify-token:
    get:
      consumes:
      - application/json
      description: Verifies the provided Firebase ID token.
      parameters:
      - description: Firebase ID Token
        in: query
        name: id_token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: Verify Firebase ID Token
      tags:
      - Auth API
  /device-tokens:
    post:
      consumes:
      - application/json
      description: Register a device token for push notifications
      parameters:
      - description: Device Info
        in: body
        name: device
        required: true
        schema:
          $ref: '#/definitions/request.RegisterDeviceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: Register a device token
      tags:
      - Device Token API
  /notification-topics:
    post:
      consumes:
      - application/json
      description: Create a new notification topic
      parameters:
      - description: Notification Topic Info
        in: body
        name: topic
        required: true
        schema:
          $ref: '#/definitions/request.CreateNotificationTopicRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: Create a notification topic
      tags:
      - Notification Topic API
  /notification-topics/subscribe:
    post:
      consumes:
      - application/json
      description: Subscribe a device to a notification topic
      parameters:
      - description: Subscription Info
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/request.SubscribeNotificationTopicRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: Subscribe to a notification topic
      tags:
      - Notification Topic API
  /notifications:
    post:
      consumes:
      - application/json
      description: Send a push notification to a device
      parameters:
      - description: Notification Info
        in: body
        name: notification
        required: true
        schema:
          $ref: '#/definitions/request.SendNotificationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: Send a notification
      tags:
      - Notification API
  /notifications/{id}/mark-read:
    patch:
      consumes:
      - application/json
      description: Mark a specific notification as read
      parameters:
      - description: Notification ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: Mark a notification as read
      tags:
      - Notification API
  /notifications/mark-all-read:
    patch:
      consumes:
      - application/json
      description: Mark all notifications as read for the current user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: Mark all notifications as read
      tags:
      - Notification API
  /notifications/me:
    get:
      consumes:
      - application/json
      description: Retrieve all notifications for a specific user
      parameters:
      - description: Filter by read status
        in: query
        name: is_read
        type: string
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of items per page
        in: query
        name: page_size
        type: integer
      - description: Field to sort by
        in: query
        name: sort
        type: string
      - description: Sort order (asc or desc)
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: Get notifications for a user
      tags:
      - Notification API
  /users:
    get:
      consumes:
      - application/json
      description: Retrieve user information
      parameters:
      - description: User Email or ID
        in: query
        name: identifier
        required: true
        type: string
      - description: Comma-separated list of related entities to preload
        in: query
        name: preload
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: Get user
      tags:
      - User API
    post:
      consumes:
      - application/json
      description: Create a new user with the provided information
      parameters:
      - description: User Info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/request.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: Create a new user
      tags:
      - User API
schemes:
- http
- https
swagger: "2.0"
